module.exports = {
  startPage: 1,
  maxPage: 100,
  routes: [
    '/quotes',
    '/quotes/tag/love', // https://www.goodreads.com/quotes/tag/inspirational-quotes?format=json&id=inspirational-quotes&mobile_xhr=1&page=2
    '/quotes/tag/life',
    '/quotes/tag/inspirational',
    '/quotes/tag/humor',
    '/quotes/tag/philosophy',
    '/quotes/tag/god',
    '/quotes/tag/truth',
    '/quotes/tag/inspirational-quotes',
    '/quotes/tag/wisdom',
    '/quotes/tag/romance',
    '/quotes/tag/happiness',
    '/quotes/tag/hope',
    '/quotes/tag/death',
    '/quotes/tag/poetry',
    '/quotes/tag/quotes',
    '/quotes/tag/faith',
    '/quotes/tag/writing',
    '/quotes/tag/inspiration',
    '/quotes/tag/religion',
    '/quotes/tag/success',
    '/quotes/tag/knowledge',
    '/quotes/tag/relationship',
    '/quotes/tag/motivation',
    '/quotes/tag/education',
    '/quotes/tag/life-lessons',
    '/quotes/tag/time',
    '/quotes/tag/science',
    '/quotes/tag/books',
    '/quotes/tag/spirituality',
    '/quotes/tag/love-quotes'
  ],
  tags: [
    'love',
    'life',
    'inspirational',
    'humor',
    'philosophy',
    'god',
    'truth',
    'inspirational-quotes',
    'wisdom',
    'romance',
    'happiness',
    'hope',
    'death',
    'poetry',
    'quotes',
    'faith',
    'writing',
    'inspiration',
    'religion',
    'success',
    'knowledge',
    'relationship',
    'motivation',
    'education',
    'life-lessons',
    'time',
    'science',
    'books',
    'spirituality',
    'love-quotes'
  ],
  maxTweetLength: 280,
  twitterCredentials: {
    consumer_key: process.env.TWITTER_CONSUMER_KEY,
    consumer_secret: process.env.TWITTER_CONSUMER_SECRET,
    access_token: process.env.TWITTER_ACCESS_TOKEN,
    access_token_secret: process.env.TWITTER_ACCESS_TOKEN_SECRET
  }
}
