module.exports = {
  startPage: 1,
  maxPage: 100,
  routes: [
    '/',
    '/tag' // https://www.goodreads.com/quotes/tag/inspirational-quotes?format=json&id=inspirational-quotes&mobile_xhr=1&page=2
  ],
  tags: [
    'love',
    'life',
    'inspirational',
    'humor',
    'philosophy',
    'god',
    'truth',
    'inspirational-quotes',
    'wisdom',
    'romance',
    'happiness',
    'hope',
    'death',
    'poetry',
    'quotes',
    'faith',
    'writing',
    'inspiration',
    'religion',
    'success',
    'knowledge',
    'relationship',
    'motivation',
    'education',
    'life-lessons',
    'time',
    'science',
    'books',
    'spirituality',
    'love-quotes'
  ]
}
